[toolchain]
	# The default profile includes rustc, rust-std, cargo, rust-docs, rustfmt and clippy.
	# https://rust-lang.github.io/rustup/concepts/profiles.html
	channel = "1.86.0"
	profile = "default"
