name: Label pull request

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pull-request:
    name: Label pull request
    runs-on: ubuntu-slim
    if: github.repository_owner == 'biomejs'
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/pull-request-labeler.yaml
