name: Label issues

on:
  issues:
    types: [ opened, reopened, edited ]

permissions:
  issues: write
  contents: read

jobs:
  label-issues:
    name: Label issue
    runs-on: ubuntu-slim
    steps:
      - name: Label documentation issues
        uses: github/issue-labeler@3431626a3aa0d4dd8cb7e3e8a03c95e45aa89d21
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-labeler.yaml
          enable-versioned-regex: 0
          sync-labels: 1
