name: Pin submodule and run codegen
on:
  workflow_dispatch:
    inputs:
      commit-id:
        description: |
          Commit ID of the submodule.
          If ommited, HEAD will be used.
        required: false
        type: string
  repository_dispatch:
    types: [biome-push-on-main-event]

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  pin-submodule-and-run-codegen:
    runs-on: ubuntu-latest
    concurrency:
      group: "pin-submodule-and-run-codegen-${{ github.event_name }}"
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          submodules: true
      - name: Get commit ID of submodule (workflow dispatch, non-empty)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit-id != '' }}
        run: echo "COMMIT_ID=${{ github.event.inputs.commit-id }}" >> $GITHUB_ENV
      - name: Get commit ID of submodule (repository dispatch)
        if: ${{ github.event_name == 'repository_dispatch'}}
        run: echo "COMMIT_ID=${{ github.event.client_payload.event.head_commit.id }}" >> "$GITHUB_ENV"
      - name: Get short commit ID
        run: echo "SHORT_COMMIT_ID=$(echo ${{ env.COMMIT_ID }} | cut -c 1-7)" >> "$GITHUB_ENV"
      - name: Run codegen
        uses: ./.github/actions/run-codegen
        with:
          kinds: metadata, rules
          version: "0.0.0"
          revision: ${{ env.COMMIT_ID }}
      - name: Deploy playground
        uses: ./.github/actions/build-playground
        with:
            revision: ${{ env.COMMIT_ID }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - name: Update playground
        run: |
          pnpm i https://pkg.pr.new/biomejs/biome/@biomejs/wasm-web@${{ env.COMMIT_ID }}
      - name: Create pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          branch: "chore/pin-submodule-and-run-codegen-${{ github.event_name }}"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          title: "chore(ci): update playground to `${{ env.SHORT_COMMIT_ID }}` and run codegen"
          commit-message: "chore(ci): update playground to `${{ env.SHORT_COMMIT_ID }}` and run codegen"
          body: "Update playground to [`${{ env.SHORT_COMMIT_ID }}`](https://github.com/biomejs/biome/commit/${{ env.COMMIT_ID }}) and run codegen."
          labels: CI-Submodule
      - name: Auto merge
        if: ${{ steps.create-pull-request.outputs.pull-request-operation != 'closed' && steps.create-pull-request.outputs.pull-request-number != '' }}
        run: gh pr merge --squash --auto --delete-branch ${{ steps.create-pull-request.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
